/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/comments/manage': RouteRecordInfo<'/comments/manage', '/comments/manage', Record<never, never>, Record<never, never>>,
    '/comments/review': RouteRecordInfo<'/comments/review', '/comments/review', Record<never, never>, Record<never, never>>,
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/friends/manage': RouteRecordInfo<'/friends/manage', '/friends/manage', Record<never, never>, Record<never, never>>,
    '/friends/review': RouteRecordInfo<'/friends/review', '/friends/review', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/posts': RouteRecordInfo<'/posts', '/posts', Record<never, never>, Record<never, never>>,
    '/projects/categories': RouteRecordInfo<'/projects/categories', '/projects/categories', Record<never, never>, Record<never, never>>,
    '/projects/manage': RouteRecordInfo<'/projects/manage', '/projects/manage', Record<never, never>, Record<never, never>>,
    '/system/settings': RouteRecordInfo<'/system/settings', '/system/settings', Record<never, never>, Record<never, never>>,
    '/system/users': RouteRecordInfo<'/system/users', '/system/users', Record<never, never>, Record<never, never>>,
    '/tags': RouteRecordInfo<'/tags', '/tags', Record<never, never>, Record<never, never>>,
  }
}
